### ISSUE TITLE
Internationalization German

### ISSUE THREAD

**Issue by wolfgangihloff** [wolfgangihloff/peergroup#19]
Enabled configuration option to run app in German or English, only one language can deployed at one time.

**Comment by wolfgangihloff** [comment]
Wolfgang will provide translation file

**Comment by kazjote** [comment]
The following files need to be translated:
-  config/locales/application_de.yml
-  db/default_rules_de.csv
-  app/views/pages/_about.de.html.haml
-  app/views/pages/_help.de.html.haml
-  README / LIESMICH

**Comment by wolfgangihloff** [comment]
Task now taken by Wolfgang.

**Comment by wolfgangihloff** [comment]
commit  bb1914a77dc0665c58e4
done
