### ISSUE TITLE
Juggernaut for Chat

### ISSUE THREAD

**Issue by wolfgangihloff** [wolfgangihloff/peergroup#24]
The current chat solution does not scale with 500+ users, thus using the Juggernaut gem for chat with Flash needs to be considered.

**Comment by kazjote** [comment]
Juggernaut is not supported by Heroku AFAIK.

We should consider Node.js http://blog.heroku.com/archives/2010/4/28/node_js_support_experimental/

**Comment by wolfgangihloff** [comment]
node.js sounds great - I will dig into it a bit more, the big benefit also is, that we do not have crappy flash in there, that is what steered me away from Juggernaut anyway.

Since it is event driven towards the browser it should scale better is my first impression.

**Comment by wolfgangihloff** [comment]
the following considerations are important:
-  no polling
-  scalability to above 500 clients
-  small server resource footprint
-  asynchronus data model update to clients
  Can that be achieved with node.js?
